package br.com.b256.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * B256 colors. https://material-foundation.github.io/material-theme-builder/
 */
internal val lightPrimary = Color(0xFFBA1A1A) //0xFF2A5BB1
internal val lightOnPrimary = Color(0xFFFFFFFF)
internal val lightPrimaryContainer = Color(0xFFD9E2FF)
internal val lightOnPrimaryContainer = Color(0xFF001A43)
internal val lightSecondary = Color(0xFF006399)
internal val lightOnSecondary = Color(0xFFFFFFFF)
internal val lightSecondaryContainer = Color(0xFFCDE5FF)
internal val lightOnSecondaryContainer = Color(0xFF001D32)
internal val lightTertiary = Color(0xFF0959C6)
internal val lightOnTertiary = Color(0xFFFFFFFF)
internal val lightTertiaryContainer = Color(0xFFD9E2FF)
internal val lightOnTertiaryContainer = Color(0xFF001944)
internal val lightError = Color(0xFFBA1A1A)
internal val lightErrorContainer = Color(0xFFFFDAD6)
internal val lightOnError = Color(0xFFFFFFFF)
internal val lightOnErrorContainer = Color(0xFF410002)
internal val lightBackground = Color(0xFFFEFBFF)
internal val lightOnBackground = Color(0xFF1B1B1F)
internal val lightSurface = Color(0xFFFEFBFF)
internal val lightOnSurface = Color(0xFF1B1B1F)
internal val lightSurfaceVariant = Color(0xFFE1E2EC)
internal val lightOnSurfaceVariant = Color(0xFF44474F)
internal val lightOutline = Color(0xFF757780)
internal val lightInverseOnSurface = Color(0xFFF2F0F4)
internal val lightInverseSurface = Color(0xFF303034)
internal val lightInversePrimary = Color(0xFFAFC6FF)
internal val lightShadow = Color(0xFF000000)
internal val lightSurfaceTint = Color(0xFF2A5BB1)
internal val lightOutlineVariant = Color(0xFFC5C6D0)
internal val lightScrim = Color(0xFF000000)

internal val darkPrimary = Color(0xFFFF897A)
internal val darkOnPrimary = Color(0xFF002D6C)
internal val darkPrimaryContainer = Color(0xFF004397)
internal val darkOnPrimaryContainer = Color(0xFFD9E2FF)
internal val darkSecondary = Color(0xFF94CCFF)
internal val darkOnSecondary = Color(0xFF003352)
internal val darkSecondaryContainer = Color(0xFF004B74)
internal val darkOnSecondaryContainer = Color(0xFFCDE5FF)
internal val darkTertiary = Color(0xFFAFC6FF)
internal val darkOnTertiary = Color(0xFF002D6D)
internal val darkTertiaryContainer = Color(0xFF004299)
internal val darkOnTertiaryContainer = Color(0xFFD9E2FF)
internal val darkError = Color(0xFFFFB4AB)
internal val darkErrorContainer = Color(0xFF93000A)
internal val darkOnError = Color(0xFF690005)
internal val darkOnErrorContainer = Color(0xFFFFDAD6)
internal val darkBackground = Color(0xFF1B1B1F)
internal val darkOnBackground = Color(0xFFE3E2E6)
internal val darkSurface = Color(0xFF1B1B1F)
internal val darkOnSurface = Color(0xFFE3E2E6)
internal val darkSurfaceVariant = Color(0xFF44474F)
internal val darkOnSurfaceVariant = Color(0xFFC5C6D0)
internal val darkOutline = Color(0xFF8E9099)
internal val darkInverseOnSurface = Color(0xFF1B1B1F)
internal val darkInverseSurface = Color(0xFFE3E2E6)
internal val darkInversePrimary = Color(0xFF2A5BB1)
internal val darkShadow = Color(0xFF000000)
internal val darkSurfaceTint = Color(0xFFAFC6FF)
internal val darkOutlineVariant = Color(0xFF44474F)
internal val darkScrim = Color(0xFF000000)
