package br.com.b256.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * B256 colors.
 */
internal val lightPrimary = Color(0xFF505151)
internal val lightOnPrimary = Color(0xFFFFFFFF)
internal val lightPrimaryContainer = Color(0xFF757575)
internal val lightOnPrimaryContainer = Color(0xFFFFFFFF)
internal val lightSecondary = Color(0xFF5E5E5E)
internal val lightOnSecondary = Color(0xFFFFFFFF)
internal val lightSecondaryContainer = Color(0xFFA3A3A3)
internal val lightOnSecondaryContainer = Color(0xFF171818)
internal val lightTertiary = Color(0xFF005581)
internal val lightOnTertiary = Color(0xFFFFFFFF)
internal val lightTertiaryContainer = Color(0xFF007BB9)
internal val lightOnTertiaryContainer = Color(0xFFFFFFFF)
internal val lightError = Color(0xFFBA1A1A)
internal val lightOnError = Color(0xFFFFFFFF)
internal val lightErrorContainer = Color(0xFFFFDAD6)
internal val lightOnErrorContainer = Color(0xFF410002)
internal val lightBackground = Color(0xFFFCF8F8)
internal val lightOnBackground = Color(0xFF1C1B1B)
internal val lightSurface = Color(0xFFFCF8F8)
internal val lightOnSurface = Color(0xFF1C1B1B)
internal val lightSurfaceVariant = Color(0xFFE0E3E3)
internal val lightOnSurfaceVariant = Color(0xFF444748)
internal val lightOutline = Color(0xFF747878)
internal val lightOutlineVariant = Color(0xFFC4C7C7)
internal val lightScrim = Color(0xFF000000)
internal val lightInverseSurface = Color(0xFF313030)
internal val lightInverseOnSurface = Color(0xFFF4F0EF)
internal val lightInversePrimary = Color(0xFFC7C6C6)
internal val lightSurfaceDim = Color(0xFFDDD9D9)

internal val darkPrimary = Color(0xFFC7C6C6)
internal val darkOnPrimary = Color(0xFF303031)
internal val darkPrimaryContainer = Color(0xFF5C5C5C)
internal val darkOnPrimaryContainer = Color(0xFFFFFFFF)
internal val darkSecondary = Color(0xFFC7C6C6)
internal val darkOnSecondary = Color(0xFF2F3131)
internal val darkSecondaryContainer = Color(0xFF747475)
internal val darkOnSecondaryContainer = Color(0xFFFFFFFF)
internal val darkTertiary = Color(0xFF92CCFF)
internal val darkOnTertiary = Color(0xFF003351)
internal val darkTertiaryContainer = Color(0xFF007BB9)
internal val darkOnTertiaryContainer = Color(0xFFFFFFFF)
internal val darkError = Color(0xFFFFB4AB)
internal val darkOnError = Color(0xFF690005)
internal val darkErrorContainer = Color(0xFF93000A)
internal val darkOnErrorContainer = Color(0xFFFFDAD6)
internal val darkBackground = Color(0xFF141313)
internal val darkOnBackground = Color(0xFFE5E2E1)
internal val darkSurface = Color(0xFF141313)
internal val darkOnSurface = Color(0xFFE5E2E1)
internal val darkSurfaceVariant = Color(0xFF444748)
internal val darkOnSurfaceVariant = Color(0xFFC4C7C7)
internal val darkOutline = Color(0xFF8E9192)
internal val darkOutlineVariant = Color(0xFF444748)
internal val darkScrim = Color(0xFF000000)
internal val darkInverseSurface = Color(0xFFE5E2E1)
internal val darkInverseOnSurface = Color(0xFF313030)
internal val darkInversePrimary = Color(0xFF5E5E5E)
internal val darkSurfaceDim = Color(0xFF141313)
